/*
 * --------------------------------------------------------------------------
 * File: login-wallet.dto.ts
 * Project: car-dano-backend
 * Copyright © 2025 PT. Inspeksi Mobil Jogja
 * --------------------------------------------------------------------------
 * Description: Data Transfer Object (DTO) for wallet login requests.
 * Defines the structure of the data expected from the client when a user
 * attempts to log in using their Cardano wallet address and a signed message.
 * --------------------------------------------------------------------------
 */

import { ApiProperty } from '@nestjs/swagger';
import { Transform } from 'class-transformer';
import { IsString, IsNotEmpty, Matches, MaxLength } from 'class-validator';

export class LoginWalletDto {
  /**
   * The user's Cardano wallet address used for login/authentication.
   * Must start with a Cardano bech32 prefix: addr1, addr_test1, stake1, or stake_test1.
   * @example "addr1qx2k8q9p5z4z..."
   */
  @ApiProperty({
    description: 'Cardano wallet address used for login',
    example: 'addr1qx2k8q9p5z4z...',
    required: true,
  })
  @Transform(({ value }: { value: unknown }) =>
    typeof value === 'string' ? value.trim() : value,
  )
  @IsString()
  @IsNotEmpty()
  @MaxLength(255)
  @Matches(/^(addr1|addr_test1|stake1|stake_test1)[a-z0-9]+$/, {
    message:
      'walletAddress must be a valid Cardano bech32 address (addr1…, addr_test1…, stake1…, or stake_test1…)',
  })
  walletAddress!: string;

  /**
   * A message signed by the user's wallet to prove ownership.
   * The backend needs to verify this signature against the walletAddress.
   * CIP-0030 signatures are JSON objects; the serialized string is bounded in practice.
   * @example '{"signature": "...", "key": "..."}'
   */
  @ApiProperty({
    description:
      "Data signature generated by the user's wallet to prove ownership",
    example: '{"signature": "...", "key": "..."}',
    required: true,
  })
  @IsString()
  @IsNotEmpty()
  // CIP-0030 wallet signatures are bounded hex/cbor strings; 4096 chars is a generous ceiling
  @MaxLength(4096, { message: 'signature must not exceed 4096 characters' })
  signature!: string;
}
