/*
 * --------------------------------------------------------------------------
 * File: blueprint.type.ts
 * Project: car-dano-backend
 * Copyright © 2025 PT. Inspeksi Mobil Jogja
 * --------------------------------------------------------------------------
 * Description: Defines data structures for Plutus blueprint and validator objects.
 * These structures are based on the plutus.json file generated by Aiken.
 * --------------------------------------------------------------------------
 */

/**
 * Defines the data structure for a validator object
 * found within the plutus.json file from Aiken.
 */
export interface PlutusValidator {
  /**
   * The title of the validator.
   */
  title: string;
  /**
   * The compiled code of the validator.
   */
  compiledCode: string;
  /**
   * The hash of the validator.
   */
  hash: string;
  // Add other properties if needed, such as 'parameters', 'redeemer', etc.
}

/**
 * Defines the main data structure of the plutus.json file.
 */
export interface PlutusBlueprint {
  /**
   * Preamble information for the blueprint.
   */
  preamble: {
    /**
     * The title of the blueprint.
     */
    title: string;
    /**
     * The version of the blueprint.
     */
    version: string;
    // ...other properties in preamble
  };
  /**
   * An array of validator objects included in the blueprint.
   */
  validators: PlutusValidator[];
  /**
   * Definitions section of the blueprint.
   */
  definitions: Record<string, any>;
}
